"""create db

Revision ID: 6b3b71e0a18a
Revises: 3ff57c9a8a78
Create Date: 2024-01-29 18:27:14.520851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3b71e0a18a'
down_revision = '3ff57c9a8a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(), nullable=True))
        batch_op.alter_column('total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('street')
        batch_op.drop_column('county')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
