"""created db

Revision ID: ee811615da67
Revises: 5d48bda1caaa
Create Date: 2024-01-18 23:19:23.399073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee811615da67'
down_revision = '5d48bda1caaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featuredbrands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageurl', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topbrands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageurl', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageurl', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topcategories')
    op.drop_table('topbrands')
    op.drop_table('featuredbrands')
    # ### end Alembic commands ###
