"""created db

Revision ID: fb9f557588b3
Revises: ee811615da67
Create Date: 2024-01-20 00:09:25.163582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9f557588b3'
down_revision = 'ee811615da67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topbrands')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topbrands',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('imageurl', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
